services:
  backend:
    build:
      context: ./taxi-service # Points to your Spring Boot app folder
      dockerfile: Dockerfile # The backend Dockerfile in taxi-service folder
    image: taxi-service-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on: # Modified to wait for db to be healthy
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./taxi-service-frontend
      dockerfile: Dockerfile
    image: taxi-service-frontend
    ports:
      - "5176:80" # Maps container port 80 (Nginx) to host port 5176
    depends_on: # frontend might depend on backend being available
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - taxi_db_data:/var/lib/mysql
    healthcheck: # healthcheck for the database
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${MYSQL_USER}",
          "-p${MYSQL_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Gives MySQL time to initialize before checks begin
    restart: unless-stopped

volumes:
  taxi_db_data:
